### ISSUE TITLE
#include "driver" Unresolved.

### ISSUE THREAD

**Issue by Playedswag** [Kl0ibi/esp32_hackingtool#17]
I am trying to add some features to the project, i can code but i am new to espressif. But i always get an error in every component including "driver". I read somewhere that you have to add "REQUIRES driver', to the idf_component_register to your Component" but i don't know how to do that.

**Comment by uCanCallSpitfire** [comment]
We want to extract the files from the compilation, change its language, and add some new features. How can we open this compilation file, and which programs can we use to edit this file?
