### ISSUE TITLE
You didn't include esl wifi lib

### ISSUE THREAD

**Issue by guavuavcycayfayqvqu** [Kl0ibi/esp32_hackingtool#37]
![IMG20240714233740](https://github.com/user-attachments/assets/6ce9de57-6bad-411c-bc36-c0bb94934e6a)

**Comment by Kl0ibi** [comment]
wrong repo.

**Comment by guavuavcycayfayqvqu** [comment]
> wrong repo.

Nooo, it's just example! Yours is facing same problems! Do i need to send your screnshot?
