### ISSUE TITLE
Esp idf component error 

### ISSUE THREAD

**Issue by guavuavcycayfayqvqu** [Kl0ibi/esp32_hackingtool#38]
No matter how i try add in cmake/dependency the error never goes. Added in photo. Sorry for dump question I'm noob. I'm building   for esp32 s3 
![Uploading IMG20240714233740.jpg…]()

**Comment by guavuavcycayfayqvqu** [comment]
https://esp32.com/viewtopic.php?f=2&t=40881

**Comment by Kl0ibi** [comment]
Hey, you are facing the issue on a repo I am not the owner of. But I'm assuming you simply installed the wrong ESP-IDF version.

**Comment by guavuavcycayfayqvqu** [comment]
> Hey, you are facing the issue on a repo I am not the owner of. But I'm assuming you simply installed the wrong ESP-IDF version.

I used latest version.

**Comment by Kl0ibi** [comment]
Please use the IDF Version as described in each description: For my project use 4.3.2 and for the other one use 4.1

**Comment by guavuavcycayfayqvqu** [comment]
> Please use the IDF Version as described in each description: For my project use 4.3.2 and for the other one use 4.1

Okay i will try and give update

**Comment by guavuavcycayfayqvqu** [comment]
![IMG20240715173036](https://github.com/user-attachments/assets/e01bc406-527e-4225-9604-4b55bf682692)
Not working

**Comment by guavuavcycayfayqvqu** [comment]
> Please use the IDF Version as described in each description: For my project use 4.3.2 and for the other one use 4.1

Can you please build for esp32 s3 and upload in github / send in my mail? I really liked your project. Please. (I can help in debug and testing in esp32 s3)

**Comment by uCanCallSpitfire** [comment]
We want to extract the files from the compilation, change its language, and add some new features. How can we open this compilation file, and which programs can we use to edit this file?
