### ISSUE TITLE
Bin file does not work

### ISSUE THREAD

**Issue by jamine16** [Kl0ibi/esp32_hackingtool#4]
I am flashing the .bin file but my esp device just shows a blank screen.

**Comment by Kl0ibi** [comment]
Thanks for creating this issue thread! 
I forgot to provide the partition-table and bootloader bin files i uploaded both in the new esptool_flash folder.
Have a look at the description I provided the full command

**Comment by uCanCallSpitfire** [comment]
We want to extract the files from the compilation, change its language, and add some new features. How can we open this compilation file, and which programs can we use to edit this file?
