### ISSUE TITLE
nothing shows up o serial terminal

### ISSUE THREAD

**Issue by bluetechx** [Kl0ibi/esp32_hackingtool#46]
i flashed firmware with esp.huhn.me but after flashing when i go to the serial terminal, this comes: "[A[A[2KHey buddy, let's get to know each other! Please enter your username" and when i enter my name and hit enter, nothing shows up. im using esp wroom 32u

**Comment by Kl0ibi** [comment]
Hi please refer to the how to use part of my ReadMe:


IMPORTANT NOTE: Ensure that your serial monitor is compatible with escape codes to guarantee accurate output display.

If you are Windows user (my condolences 🥲). CMD not displays output correctly. As an alternative, consider using Putty or a similar program
